COP-6
MetisoftSolutions/metisoft-node-firebase-util pull request #1
Opened 2019-02-06 03:08 UTC by andrew-ironforge

https://metisoft.atlassian.net/browse/COP-6

2019-02-07 11:21 UTC, andrew-ironforge commented on package.json
> +    "firebase-admin": "^7.0.0"
Upgraded to support rich notifications. Earlier versions of firebase did not

2019-02-07 19:37 UTC, jbrawnjr requested changes

2019-02-07 19:37 UTC, jbrawnjr commented on src/index.ts
> +  richOptions?: IRichNotificationOptions;
`richNotificationOptions`

2019-02-07 19:37 UTC, jbrawnjr commented on src/index.ts
> +        notification: {
Now that we have a lot more logic in this section, let's make a function `__genFirebaseMessage()` that takes `firebaseToken` and `ISendPushNotificationOptions` and returns `admin.messaging.Message`.

2019-02-07 19:37 UTC, jbrawnjr commented on src/index.ts
> +  let serviceAccount = require(opts.pathToServiceAccountKey);
`opts` -> `__options`

2019-02-07 19:37 UTC, jbrawnjr commented on src/index.ts
> +    databaseURL: opts.databaseUrl
`opts` -> `__options`

2019-02-08 02:04 UTC, jbrawnjr approved these changes

2019-02-08 02:04 UTC, merged